### ISSUE TITLE
Can't login on mac m1 if you have OTP

### ISSUE THREAD

**Issue by arthur-trt** [horiz0n-zero/42-Home#1]
On mac m1 we can't login if OTP is enable. Indeed after login a popup open telling we have uncacth redirection, if you click on the link it will open a browser tab (brave for me) ask for OTP but connection will not follow on the application. 

<img width="291" alt="Screenshot 2022-10-14 at 10 20 31" src="https://user-images.githubusercontent.com/4441676/195798597-b06543c1-b856-4ea6-bccb-51d229d41ab1.png">

**Comment by horiz0n-zero** [comment]
The 2 Factor Authentification is currently not supported by the application, but it be supported soon enough in a next update ;-)

**Comment by horiz0n-zero** [comment]
2FA is now supported, please just wait for the next update parution on the next appstore
