### ISSUE TITLE
Projects and Exams are showed with a wrong color or score in a User's Profile

### ISSUE THREAD

**Issue by SubliminalMessage** [horiz0n-zero/42-Home#2]
I think it's a bad handled API result, but just in case you need it:
**App Version:** `1.0.5`
**Device:** `iPhone 12, running iOS 16.0.2`

### Description:
When entering a User's profile, the score of the Exam is `100` if the Exam didn't even start yet.
In addition to that, while the Project' scores are OK, the color that determines if those projects are validated or not (green / red) might not be correct. **Note:** I've only seen this behaviour on Students doing the Piscine. Not sure if this issue occurs also on Students on different Cursus.

I assume there is a bad reading of the API fetch result.
The flag `validated` tells you wheter the project is validated or not (wheter the color should be green or red).
You can check it out on the API documentation: https://api.intra.42.fr/apidoc/2.0/projects_users/index.html

### How to reproduce the issue:

1. Search for a Student doing the Piscine
2. Go to the 'Ended' section
3. Contrast the results with the ones the Intra gives you 

### Screenshots:
```
App Language was 'Spanish' when the Screenshots were taken.
The Users' login is not shown to protect their privacity.
```
**42Home App**
![b9a39e7f-3e36-42dd-9de7-f15d3334f924](https://user-images.githubusercontent.com/71818186/200924106-a2e43644-f0eb-4f90-bd34-181380e56b52.jpg)

**42 Intra**
![ff7a8584-0587-48ca-84bd-b77c108b4406](https://user-images.githubusercontent.com/71818186/200924122-c31a0bc4-51d8-4acf-ad0c-a9b85c58d6a8.jpg)

```
Note that the following projects are not correctly shown: 
* C Piscine Exam 01 -> (not started yet)
* C Piscine Shell 01 -> (should be green, project appears as validated on the Intra)
```

**Comment by horiz0n-zero** [comment]
Hello
Thanks for your report :-)

The app handle score in the old way but exception can always occured:
if score < 75
-> u failed ( red color )
else if score != 125
-> success ( green color )
else
-> success high score ( gold color ) 
the app doesn't take into account the "validated" field so u have a really good point where;

A fix is needed ! 

Envoyé de mon iPhone

**Comment by horiz0n-zero** [comment]
Hello

It's seem to be ok :-) 
The state "waiting_to_start" was not taken into account.
The "validated?" ( f*** the '?') field is now supported

![IMG_0620](https://user-images.githubusercontent.com/20483430/202841807-b3a13196-0f8f-4817-8491-c2692b646b6b.png)
