### ISSUE TITLE
cluster 3 update from Prague 42 campus

### ISSUE THREAD

**Issue by xhelp00** [horiz0n-zero/42-Home#27]
Hi, could you please update cluster 3 at Prague campus? We have added new stations here. Thanks!
https://cdn.intra.42.fr/cluster/image/197/cluster_3.svg
![cluster_3](https://github.com/horiz0n-zero/42-Home/assets/111277585/56b117fe-8e81-43e4-ba82-94264735fa69)

**Comment by horiz0n-zero** [comment]
Hello ;-) 

Could you send me also, the others .svg and the name you give to all individual cluster 

Thanks

**Comment by xhelp00** [comment]
Sure, it is nothing fancy, just:

Cluster 1
Cluster 2
Cluster 3

https://cdn.intra.42.fr/cluster/image/191/cluster_1.svg
https://cdn.intra.42.fr/cluster/image/192/cluster_2.svg
https://cdn.intra.42.fr/cluster/image/197/cluster_3.svg

Many thanks!

**Comment by horiz0n-zero** [comment]
Hello i've waited Paris clusters update to do the work;
now it's done and waiting for approbation in the appstore

**Comment by xhelp00** [comment]
merci beaucoup!
