### ISSUE TITLE
Unable to log in.

### ISSUE THREAD

**Issue by yoamzil** [horiz0n-zero/42-Home#32]
Warning : internal error cookies are invalid https://profile.intra.42.fr

**Comment by horiz0n-zero** [comment]
Hello Thanks for the reporting !

A change in the following page https://profile.intra.42.fr/users/:login have produce a cookie verification issue.
Verification moved to the https://translate.intra.42.fr/users/:login/locations_stats.json root.

Please wait for the update ;-)
