### ISSUE TITLE
User

### ISSUE THREAD

**Issue by ftemori** [horiz0n-zero/42-Home#33]
Since almost 2 months I am not able to use the 42home app. Everytime I try to login, it gives me an error message but I also get an email from intra that I was logged in.
I will attach a screenshot
![image](https://github.com/user-attachments/assets/275b9852-7979-4d94-9f8c-23392d9272cf)

Kind regards

**Comment by horiz0n-zero** [comment]
Hello the API secret have been changed, since 15 days. I updated with the correct new secret 
Thanks for reporting !

**Comment by ftemori** [comment]
Hi, I am still not able to use the app tho. Same error message everytime I try to login.It feels like I cannot login, because I somehow already am logged in. If there was some way to delete the cache or log me out from all the sessions, that could help I guess.
Thanks


Sent from Yahoo Mail for iPhone


On Wednesday, August 7, 2024, 9:19 AM, horiz0n-zero ***@***.***> wrote:




Hello the API secret have been changed, since 15 days. I updated with the correct new secret
Thanks for reporting !

**Comment by horiz0n-zero** [comment]
Hello, at the moment you wrote your message, the appstore still doesn't have finish to review the update i push.
Actually at the time i'm responding to you, the app as been approved and we can see it on the appstore ( version 1.1.9 ).
You can now simply update your app, and if u continue to have troubles juste delete and redownload the app.

Best regards

**Comment by horiz0n-zero** [comment]
This i why i added the "Waiting for update" tag

**Comment by ftemori** [comment]
Hey,it works now thank you.Also we got a new cluster on our campus in Berlin around 5 months ago, which is not shown on the app but only on intra. I was wondering if you could add that. The new cluster is called “c3a”


Thanks a lot

Sent from Yahoo Mail for iPhone


On Wednesday, August 7, 2024, 1:34 PM, horiz0n-zero ***@***.***> wrote:




This i why i added the "Waiting for update" tag

**Comment by horiz0n-zero** [comment]
Ok perfect 👍, i close the issue.
if u want an update about your clusters, please give me the all .svg files you can found at https://meta.intra.42.fr/clusters
with the related cluster name for each file. And i will regenerate a description based on the file so you can see in the next update yours clusters up to date ;-) please send files at antoinefeufeu@gmail.com thanks
