### ISSUE TITLE
APP CRASH AFTER LOG IN

### ISSUE THREAD

**Issue by apaz-dev** [horiz0n-zero/42-Home#34]
Hello
When I log in to the application it crashes but before it crashes I see for 1 second what would be the app before it crashes.
I'm using an iphone xr with ios 17

**Comment by horiz0n-zero** [comment]
mmmmh ... no crash on my side. But the V2 API due to V3 progressive landing cause issues that needs to be investigate ...
Why do you close the issue ? The probleme appear once ?
