### ISSUE TITLE
User Profil - Show user title and user full name by default

### ISSUE THREAD

**Issue by horiz0n-zero** [horiz0n-zero/42-Home#8]
When i access to a user profil; i see the login; and if i click into it; i can see the user full name 

Now by default; we should see user full name instead of login;
and when i click a third time; we can see the primary user title if available.

Need a new option in settings:
'default user text':
> 'Full name' ( default )
> 'login'
> 'title'

Add by default title if the user is a staff ?

**Comment by 42mgr** [comment]
Top!
